# Generated by Django 4.2.7 on 2023-11-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digestapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcategory',
            old_name='date',
            new_name='timestamp',
        ),
    ]
